version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_assignment
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/altamerics
    command: npm run start

volumes:
  postgres_data:
    driver: local